/**
 * PHASE 0 â€” SAFETY NET (2/2): GOLDEN FORMULA FIXTURES
 *   npx tsx tests/formulaGolden.test.ts
 *
 * PURPOSE (Phase 0 of the Universal MÃ©trÃ© engine):
 *   Record and lock the CURRENT, considered-correct output of the 12 official
 *   calculators + the generic branch, so a later phase can PROVE the new
 *   engine did not alter any historical result.
 *
 * HOW THE FIXTURES WERE PRODUCED (important):
 *   `tests/fixtures/formulas/golden.json` was generated by executing the REAL
 *   calculators once (temporary generator, removed after use). It is a RECORD
 *   of current behaviour â€” NOT a hand-computed or re-derived expectation.
 *   This test then RE-PLAYS those exact inputs and asserts the output is
 *   byte-identical to the record.
 *
 * DESIGN RULES:
 *   - It NEVER rewrites a formula and never recomputes an expectation.
 *   - Inputs live in this file (explicit, reviewable); outputs live in the
 *     JSON record. A formula change therefore fails loudly here.
 *   - Numeric comparison is EXACT (===) on every field: golden tests are not
 *     "approximately equal". Float noise is part of the frozen behaviour.
 *   - DB-free: no database, no server, no network, no file import.
 *
 * SCOPE: read-only. Nothing in src/, server/ or the DB is touched.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as calc from '../src/utils/calculations';
import { DEFAULT_MARKET_RATES } from '../src/data/marketRates';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const GOLDEN = JSON.parse(
  fs.readFileSync(path.join(HERE, 'fixtures', 'formulas', 'golden.json'), 'utf8'),
) as Record<string, any>;

const R = DEFAULT_MARKET_RATES;
const FISCAL = { tvaPercent: 19, includeTimbre: true, retenueGarantiePercent: 5 };

let passed = 0;
let failed = 0;
const failures: string[] = [];

async function test(name: string, fn: () => void | Promise<void>) {
  try {
    await fn();
    passed++;
    console.log(`  PASS ${name}`);
  } catch (err: any) {
    failed++;
    const msg = `  FAIL ${name}\n       ${err?.message || err}`;
    failures.push(msg);
    console.log(msg);
  }
}

/**
 * Compare a fresh calculator result against the recorded one.
 * Every material line and every scalar must match EXACTLY.
 */
function sameAsGolden(key: string, actual: any) {
  const expected = GOLDEN[key];
  if (!expected) throw new Error(`no golden record for "${key}" â€” fixture missing`);
  for (const f of ['trade', 'subType', 'areaM2', 'netAreaM2', 'perimeterM',
    'totalMaterialTnd', 'estimatedLaborTnd', 'grandTotalTnd',
    'wasteMarginPercent', 'tvaPercent', 'tvaAmountTnd', 'timbreFiscalTnd',
    'retenueGarantiePercent', 'retenueGarantieTnd', 'totalTtcTnd', 'netAPayerTnd']) {
    if (actual[f] !== expected[f]) {
      throw new Error(`${key}.${f} changed: was ${expected[f]}, now ${actual[f]}`);
    }
  }
  if (!Array.isArray(actual.materialItems) || actual.materialItems.length !== expected.materialItems.length) {
    throw new Error(
      `${key}.materialItems length changed: was ${expected.materialItems.length}, now ${(actual.materialItems || []).length}`,
    );
  }
  actual.materialItems.forEach((it: any, i: number) => {
    const e = expected.materialItems[i];
    for (const f of ['id', 'qty', 'unit', 'unitPriceTnd', 'totalTnd', 'category']) {
      if (it[f] !== e[f]) throw new Error(`${key}.materialItems[${i}].${f} changed: was ${e[f]}, now ${it[f]}`);
    }
    if ((it.formulaUsed ?? null) !== (e.formulaUsed ?? null)) {
      throw new Error(
        `${key}.materialItems[${i}].formulaUsed changed:\n         was ${e.formulaUsed}\n         now ${it.formulaUsed}`,
      );
    }
  });
}

console.log('\nâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•');
console.log(' PHASE 0 â€” GOLDEN FORMULA FIXTURES (current behaviour, frozen)');
console.log('â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•\n');
// â”€â”€ 1) PLACO (3 fixtures: cloisons, faux plafond, non-deductible opening) â”€â”€â”€â”€
const PLACO_BASE: any = {
  subType: 'cloison_fixe', length: 5, heightOrWidth: 2.8,
  openingsCount: 1, openingArea: 1.68,
  boardType: 'plaque_ba13_standard', boardThickness: '12.5mm', boardDimension: '120x250',
  studType: '48mm', skinType: 'two_sides_single_skin', montantsSpacingCm: 60,
  withInsulation: false, wasteMarginPercent: 10, laborRatePerM2: 18, ...FISCAL,
};

await test('golden placo: cloison_fixe (net area deducts a 1.68 mÂ² opening)', () => {
  sameAsGolden('placo_cloison_fixe', calc.calculatePlaco({ ...PLACO_BASE }, R));
});

await test('golden placo: faux_plafond_ba13 branch, no openings', () => {
  sameAsGolden('placo_faux_plafond_ba13', calc.calculatePlaco(
    { ...PLACO_BASE, subType: 'faux_plafond_ba13', openingsCount: 0, openingArea: 0 }, R));
});

await test('golden placo: openings < 1 mÂ² are NOT deducted (Tunisian usage)', () => {
  sameAsGolden('placo_opening_under_1m2', calc.calculatePlaco(
    { ...PLACO_BASE, openingsCount: 2, openingArea: 0.8 }, R));
});

// â”€â”€ 2) PEINTURE (2 fixtures) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
await test('golden peinture: 2 coats, surfaceCondition normal', () => {
  sameAsGolden('peinture', calc.calculatePeinture({
    length: 6, height: 2.8, openingsArea: 3,
    paintType: 'peinture_acrylique_10l', rendementM2L: 10, coats: 2,
    surfaceCondition: 'normal', wasteMarginPercent: 10, laborRatePerM2: 8, ...FISCAL,
  } as any, R));
});

await test('golden peinture: 3 coats, rough surface (rendement penalty 1.35)', () => {
  sameAsGolden('peinture_rough_3coats', calc.calculatePeinture({
    length: 10, height: 3, openingsArea: 2.5,
    paintType: 'peinture_satinee_10l', rendementM2L: 10, coats: 3,
    surfaceCondition: 'rough', wasteMarginPercent: 5, laborRatePerM2: 9,
  } as any, R));
});

// â”€â”€ 3) CARRELAGE (2 fixtures) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
await test('golden carrelage: pose droit 60x60', () => {
  sameAsGolden('carrelage', calc.calculateCarrelage({
    length: 5, width: 4, tileFormat: '60x60', poseType: 'droit',
    tileType: 'carreau_grand_60x60', wasteMarginPercent: 10, laborRatePerM2: 22, ...FISCAL,
  } as any, R));
});

await test('golden carrelage: pose diagonale 30x30, 15% waste', () => {
  sameAsGolden('carrelage_diagonale', calc.calculateCarrelage({
    length: 5, width: 4, tileFormat: '30x30', poseType: 'diagonale',
    tileType: 'carreau_standard_30x30', wasteMarginPercent: 15, laborRatePerM2: 28,
  } as any, R));
});

// â”€â”€ 4) MACONNERIE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
await test('golden maconnerie: brique 12 trous, openings deducted', () => {
  sameAsGolden('maconnerie', calc.calculateMaconnerie({
    length: 8, height: 3, openingsArea: 2, type: 'brique_12trous',
    wasteMarginPercent: 8, laborRatePerM2: 15, ...FISCAL,
  } as any, R));
});

// â”€â”€ 5) PLOMBERIE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
await test('golden plomberie: PPR, 6 points, 25 ml network', () => {
  sameAsGolden('plomberie', calc.calculatePlomberie({
    pointsCount: 6, networkLengthM: 25, pipeType: 'ppr',
    wasteMarginPercent: 10, laborRatePerPoint: 45, ...FISCAL,
  } as any, R));
});

// â”€â”€ 6) ELECTRICITE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
await test('golden electricite: 90 mÂ², points + prises + force lines', () => {
  sameAsGolden('electricite', calc.calculateElectricite({
    areaM2: 90, lightPointsCount: 14, powerOutletsCount: 18, forceLinesCount: 2,
    wasteMarginPercent: 10, laborRatePerPoint: 25, ...FISCAL,
  } as any, R));
});

// â”€â”€ 7) ETANCHEITE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
await test('golden etancheite: membrane bitumineuse, acrotÃ¨re perimeter', () => {
  sameAsGolden('etancheite', calc.calculateEtancheite({
    areaM2: 120, acroterePerimeterM: 46, system: 'membrane_bitumineuse',
    wasteMarginPercent: 10, laborRatePerM2: 18, ...FISCAL,
  } as any, R));
});

// â”€â”€ 8) ISOLATION â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
await test('golden isolation: laine de verre 50mm', () => {
  sameAsGolden('isolation', calc.calculateIsolation({
    areaM2: 85, insulationType: 'laine_de_verre_50mm',
    wasteMarginPercent: 10, laborRatePerM2: 16, ...FISCAL,
  } as any, R));
});

// â”€â”€ 9) MENUISERIE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
await test('golden menuiserie: 4 porte-fenÃªtre alu', () => {
  sameAsGolden('menuiserie', calc.calculateMenuiserie({
    subType: 'porte_fenetre_alu', unitsCount: 4, doorWidthM: 1.2, doorHeightM: 2.1,
    wasteMarginPercent: 5, laborRatePerUnit: 80, ...FISCAL,
  } as any, R));
});

// â”€â”€ 10) SOLS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
await test('golden sols: parquet stratifiÃ© 45 mÂ²', () => {
  sameAsGolden('sols', calc.calculateSols({
    areaM2: 45, solType: 'parquet_stratifie',
    wasteMarginPercent: 10, laborRatePerM2: 12, ...FISCAL,
  } as any, R));
});

// â”€â”€ 11) FACADE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
await test('golden facade: net area = 150 âˆ’ 18 mÂ² openings', () => {
  const res = calc.calculateFacade({
    areaM2: 150, openingsArea: 18, type: 'enduit_monocouche',
    wasteMarginPercent: 10, laborRatePerM2: 18, ...FISCAL,
  } as any, R);
  sameAsGolden('facade', res);
  if (res.netAreaM2 !== 132) throw new Error(`faÃ§ade netAreaM2 must stay 132, got ${res.netAreaM2}`);
});

// â”€â”€ 12) DEMOLITION â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
await test('golden demolition: cloison brique/placo 15 cm', () => {
  sameAsGolden('demolition', calc.calculateDemolition({
    areaM2: 60, thicknessCm: 15, type: 'cloison_brique_placo',
    wasteMarginPercent: 10, laborRatePerM2: 8, ...FISCAL,
  } as any, R));
});

// â”€â”€ 13) FISCAL HELPER (computeFiscalData) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
function sameFiscal(key: string, out: any) {
  const e = GOLDEN[key];
  for (const f of Object.keys(e)) {
    if (out[f] !== e[f]) throw new Error(`${key}.${f} changed: was ${e[f]}, now ${out[f]}`);
  }
}

await test('golden fiscal: 1000 materials + 500 labor, TVA 19 / timbre / retenue 10', () => {
  sameFiscal('fiscal_full', calc.computeFiscalData(1000, 500, {
    tvaPercent: 19, includeTimbre: true, retenueGarantiePercent: 10,
  }));
});

await test('golden fiscal: defaults are 0 (no TVA, no timbre, no retenue)', () => {
  const out = calc.computeFiscalData(123.456, 78.9, {});
  sameFiscal('fiscal_defaults', out);
  if (out.tvaPercent !== 0 || out.timbreFiscalTnd !== 0) throw new Error('fiscal defaults changed');
});

await test('golden fiscal: TVA 7 on a zero base stays exactly 0', () => {
  sameFiscal('fiscal_seven', calc.computeFiscalData(0, 0, {
    tvaPercent: 7, includeTimbre: false, retenueGarantiePercent: 5,
  }));
});

// â”€â”€ 14) GENERIC BRANCH (genericQty per-unit rules + placeholder) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
const g = (id: string, unit: string): any => ({
  id, category: 'gold', trade: 'gold', nameFr: id, nameAr: '', nameEn: null,
  unit, unitPriceTnd: 10, defaultPriceTnd: 10,
});
const GENERIC_RATES: any[] = [
  g('u_m2', 'm²'), g('u_ml', 'ml'), g('u_m', 'm'), g('u_m3', 'm³'), g('u_kg', 'kg'),
  g('u_litre', 'litre'), g('u_unit', 'unit'), g('u_set', 'set'), g('u_point', 'point'),
  g('u_panneau', 'panneau'), g('u_sac', 'sac'), g('u_boite', 'boite'),
  g('u_rouleau', 'rouleau'), g('u_tube', 'tube'),
];

await test('golden generic: every genericQty unit rule (area 30 / length 12 / waste 10%)', () => {
  sameAsGolden('generic_all_units', calc.calculateGeneric(
    { trade: 'gold', areaM2: 30, lengthM: 12, wasteMarginPercent: 10, laborRatePerM2: 7 } as any,
    GENERIC_RATES,
  ));
});

await test('golden generic: unknown trade yields exactly ONE zero-price placeholder', () => {
  const res = calc.calculateGeneric(
    { trade: 'nothing_here', areaM2: 30, wasteMarginPercent: 0, laborRatePerM2: 5 } as any, R,
  );
  sameAsGolden('generic_no_materials', res);
  if (res.materialItems.length !== 1) throw new Error('placeholder count must stay 1');
  if (res.materialItems[0].unitPriceTnd !== 0) throw new Error('placeholder price must stay 0');
});

// â”€â”€ Summary â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
console.log('\nâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•');
console.log(` Golden fixtures: ${passed} passed, ${failed} failed`);
console.log('â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•\n');
if (failures.length > 0) {
  console.log('FAILED TESTS:');
  failures.forEach((f) => console.log(f));
  console.log('');
}
process.exit(failed > 0 ? 1 : 0);
